foodgram/foodgram/urls.py
import debug_toolbar
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from foodgram import settings

handler404 = "foodgram.views.page_not_found" # noqa
handler500 = "foodgram.views.server_error" # noqa


urlpatterns = [
    # Регистрация/авторизация
    path("auth/", include("apps.users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    # Админка
    path('admin/', admin.site.urls),
    path('about/', include("apps.about.urls")),

    path('api/', include("apps.api.urls")),

    # Остальные урлы
    path('', include('apps.recipes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

foodgram/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Регистрация
    path("signup/", views.SignUp.as_view(), name="signup")
]

foodgram/recipes/models.py
from datetime import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

from .utility import translate_rus_eng


User = get_user_model()


class Components(models.Model):
    # Таблица компонентов
    name = models.CharField(
        db_index=True,
        max_length=100,
        unique=True,
        verbose_name='Название ингредиента',
        help_text='Название ингредиента, максимум 100 символов'
    )
    unit = models.CharField(
        max_length=20,
        verbose_name='Единица измерения',
        help_text='Единица измерения, максимум 20 симоволов'
    )

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(
        max_length=20,
        verbose_name='Тег',
        help_text='Тег рецепта, максимум 20 символов',
    )
    display_name = models.CharField(
        max_length=50,
        verbose_name='Название тега для HTML',
        blank=True
    )
    color = models.CharField(
        max_length=20,
        verbose_name='Цвет тега',
        blank=True
    )

    def __str__(self):
        return self.name


class Recipe(models.Model):
    # Основаная таблица, книга рецептов
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор',
        )
    name = models.CharField(
        max_length=100,
        verbose_name='Название рецепта',
        help_text='Максимальная длинна 100 символов',
        )
    image = models.ImageField(
        upload_to='recipes/',
        help_text='Изображение',
        verbose_name='Изображение',
        )
    description = models.TextField(
        blank=True,
        verbose_name='Описание',
        help_text='Описание рецепта',
        )
    ingredients = models.ManyToManyField(
        Components,
        through='Amount',
        through_fields=('recipe', 'ingredient'),
        verbose_name='Игредиенты',
        help_text='Игредиенты',
    )
    time_cooking = models.PositiveSmallIntegerField(
        verbose_name='Вермя приготовления'
        )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата публикации',
        )
    fav_counter = models.PositiveSmallIntegerField(
        verbose_name='Добавление в избранное',
        help_text='Количество добавлений в избранное',
        default=0,
        )
    tag = models.ManyToManyField(
        Tag,
        verbose_name='Теги',
        help_text='Тег рецепта',
    )
    slug = models.SlugField(
        max_length=500,
        unique=True,
        blank=True,
        )

    class Meta:
        ordering = ("-fav_counter", "-pub_date",)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = translate_rus_eng(self.name) + '_' + datetime.strftime(
                timezone.now(), '%d_%m_%y_%H_%M_%S_%s'
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Amount(models.Model):
    amount = models.DecimalField(
        max_digits=6,
        decimal_places=1,
        validators=[MinValueValidator(1)]
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        verbose_name='Рецепт',
        help_text='Рецепт'
    )
    ingredient = models.ForeignKey(
        Components,
        on_delete=models.CASCADE,
        related_name='+',
        verbose_name='Ингредиент',
        help_text='Ингредиент'
    )



class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorites',
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='related_recipes',
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        unique_together = ('user', 'author')

foodgram/templates/author_recipe.html
{% extends "include/base.html" %}
{% load user_filters %}
{% block title %}Рецепты автора{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}
{% block header %}
{% include "include/header.html" %}
{% endblock %}
{% block content %}
{% csrf_token %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{ author.get_full_name }}</h1>
            {% include 'include/tags.html' %}
        </div>
<!--        <p style="padding: 0 0 2em 0;"><a class="button button_style_light-blue" href="#">Подписаться на автора</a></p>-->
        {% if user != author and user.is_authenticated %}
            <div class="author-subscribe" data-author="{{ author.pk }}">
                <p style="padding: 0 0 2em 0;">
                {% if user|sub_to:author %}

                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe">
                        Отписаться от автора
                    </button>
                {% else %}
                    <button  class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>
                        Подписаться на автора
                    </button>
                {% endif %}
                </p>
            </div>
        {% endif %}
        <div class="card-list" >
            {% for recipe in page %}
                {% include "include/recipe_card.html" %}
            {% endfor %}

    </div>
        {% if page.has_other_pages %}
            {% include "include/paginator.html" with items=page paginator=paginator %}
        {% endif %}
    </main>
{% endblock content %}
{% block footer %}
{% include "include/footer.html" %}
{% endblock %}
{% block style %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock style %}

foodgram/templates/author_recipes.html
{% extends "include/base.html" %}
{% load user_filters %}
{% block title %}Рецепты автора{% endblock %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}
{% block header %}
{% include "include/header.html" %}
{% endblock %}
{% block content %}
{% csrf_token %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{{ author.get_full_name }}</h1>
            {% include 'include/tags.html' %}
        </div>
        {% if user != author and user.is_authenticated %}
            <div class="author-subscribe" data-author="{{ author.pk }}">
                <p style="padding: 0 0 2em 0;">
                {% if user|sub_to:author %}

                    <button class="button button_style_light-blue button_size_subscribe" name="subscribe">
                        Отписаться от автора
                    </button>
                {% else %}
                    <button  class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>
                        Подписаться на автора
                    </button>
                {% endif %}
                </p>
            </div>
        {% endif %}
        <div class="card-list" >
            {% for recipe in page %}
                {% include "include/recipe_card.html" %}
            {% endfor %}

    </div>
        {% if page.has_other_pages %}
            {% include "include/paginator.html" with items=page paginator=paginator %}
        {% endif %}
    </main>
{% endblock content %}
{% block footer %}
{% include "include/footer.html" %}
{% endblock %}
{% block style %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock style %}

foodgram/templates/cart.html
{% extends "include/base.html" %}
{% load user_filters %}
{% block title %}Список покупок{% endblock %}
{% load static %}
{% load thumbnail %}
{% block css %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block header %}
{% include "include/header.html" %}
{% endblock %}

{% block content %}
<main class="main container">
    {% if recipes %}
        <div class="main__header">
            <h1 class="main__title">Список покупок</h1>
        </div>
        <div class="card-list card-list_column">
            <ul class="shopping-list">
                {% for recipe in recipes %}
                    <li class="shopping-list__item" data-id="{{ recipe.id }}">
                        <div class="recipe recipe_reverse">
                            {% thumbnail recipe.item.image "480x480" as im %}
                                <img src="{{ im.url }}" alt="Картинка" class="recipe__image recipe__image_big">
                            {% endthumbnail %}
                        <h3 class="recipe__title">{{ recipe.item.name }}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.item.time_cooking }} мин.</p>
                        </div>
                        <a href="{% url 'remove_recipe_from_cart' recipe.item.id %}" class="shopping-list__button link">Удалить</a>
                    </li>
                {% endfor %}

            </ul>
            <a href="{% url 'download' %}"><button class="button button_style_blue">Скачать список</button></a>
            {% else %}
                <div class="main__header">
                    <h1 class="main__title">Корзина пуста</h1>
                </div>
            {% endif %}


        </div>
</main>
{% endblock content %}

{% block footer %}
{% include "include/footer.html" %}
{% endblock %}

{% block style %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'shopList.js' %}"></script>
{% endblock style %}

foodgram/templates/favorite.html
{% extends "include/base.html" %}
{% load user_filters %}
{% block title %}
    Избранное
{% endblock %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

<body class="body">
{% block header %}
    {% include "include/header.html" %}
{% endblock %}

{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            {% include 'include/tags.html' %}

        </div>

        <div class="card-list">
            {% for recipe in page %}
                {% include "include/recipe_card.html" %}
            {% endfor %}
        </div>
        {% if page.has_other_pages %}
            {% include "include/paginator.html" with items=page paginator=paginator %}
        {% endif %}
    </main>
{% endblock content %}

{% block footer %}
    {% include "include/footer.html" %}
{% endblock %}

{% block style %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock style %}
</body>

foodgram/templates/formRecipe.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Создание рецепта</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Избранное</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter"></span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Выход</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="breakfast" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="lunch" id="id_lunch" class="tags__checkbox tags__checkbox_style_green" checked>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" checked>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="name" class="form__input">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="file" id="id_file">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
<script src="./js/config/config.js"></script>
<script src="./js/components/Header.js"></script>
<script src="./js/utils/debouncing.js"></script>
<script src="./js/api/Api.js"></script>
<script src="formRecipe.js"></script>
</body>
</html>

foodgram/templates/form_recipe.html
{% extends "include/base.html" %}

{% load static %}
{% load user_filters %}

{% block title %}
  {% if edit %}
    Редактирование рецепта
  {% else %}
    Создание рецепта
  {% endif %}
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'pages/form.css' %}">{% endblock %}

{% block header %}{% include "include/header.html" %}{% endblock %}

{% block content %}
  <main class="main container">
    <div class="main__header">
      {% if edit %}
        <h1 class="main__title">Редактирование рецепта</h1>
      {% else %}
        <h1 class="main__title">Создание рецепта</h1>
      {% endif %}

    </div>
    <div class="form-container">
      <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form__group">
          <label class="form__label">{{ form.name.label }}</label>
          <div class="form__field-group">
            {{ form.name }}
            {% if form.errors %}
              {% for error in form.title.errors %}
                <span class="form__error">{{ error|escape }}</span>
              {% endfor %}
            {% endif %}
          </div>
        </div>
        <div class="form__group">
          <p class="form__label">{{ form.tag.label }}</p>
          <div class="form__field-group">

            <div class="tags">
              <div class="tags__item">
                <input type="checkbox" name="breakfast" id="id_breakfast"
                       class="tags__checkbox tags__checkbox_style_orange"
                    {% for i in tags %}
                      {% if i.name == "breakfast" %}
                       checked
                      {% endif %}
                    {% endfor %}>
                <label for="id_breakfast" class="tags__label">Завтрак</label>
              </div>
              <div class="tags__item">
                <input type="checkbox" name="lunch" id="id_lunch"
                       class="tags__checkbox tags__checkbox_style_green"
                    {% for i in tags %}
                      {% if i.name == "lunch" %}
                       checked
                      {% endif %}
                    {% endfor %}>
                <label for="id_lunch" class="tags__label">Обед</label>
              </div>
              <div class="tags__item">
                <input type="checkbox" name="dinner" id="id_dinner"
                       class="tags__checkbox tags__checkbox_style_purple"
                    {% for i in tags %}
                      {% if i.name == "dinner" %}
                       checked
                      {% endif %}
                    {% endfor %}>
                <label for="id_dinner" class="tags__label">Ужин</label>
              </div>
            </div>

            {% for errors in form.non_field_errors %}
              {% if errors == "Необходимо выбрать тип блюда!" %}
                <span class="form__error">{{ errors }}</span>
              {% endif %}
            {% endfor %}

          </div>
        </div>
        <div class="form__group">
          <label for="nameIngredient" class="form__label">Ингредиенты</label>
          <div class="form__field-group">
            <div class="form__field-group-ingredientes">
              <div class="form__dropdown">
                <input type="text" id="nameIngredient" class="form__input">
                <div class="form__dropdown-items"></div>
              </div>
              <input type="number" id="cantidad" class="form__input" min="0">
              <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
            </div>

            <div class="form__field-group-ingredientes-container">
              {% for i in recipe.recipe_ingredients.all %}
                <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                  <span> {{ i.ingredient.name }} {{ i.amount }} {{ i.ingredient.unit }}</span> <span
                    class="form__field-item-delete"></span>
                  <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}"
                         type="hidden" value="{{ i.ingredient.name }}">
                  <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}"
                         type="hidden" value="{{ i.amount }}">
                  <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}"
                         type="hidden" value="{{ i.ingredient.unit }}"></div>
              {% endfor %}
            </div>

            <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
            {% for errors in form.non_field_errors %}
              {% if errors != "Необходимо выбрать тип блюда!"%}
                <span class="form__error">{{ errors|escape }}</span>
              {% endif %}
            {% endfor %}
          </div>
        </div>
        <div class="form__group">
          <label class="form__label">{{ form.time_cooking.label }}</label>
          <div class="form__field-group form__field-group_time">
            {{ form.time_cooking }}
            <label class="form__label">минут</label>
          {% if form.errors %}
            {% for field in form %}
              {% for errors in field.errors %}
                <span class="form__error">{{ errors|escape }}</span>
              {% endfor %}
            {% endfor %}
          {% endif %}

          </div>
        </div>
        <div class="form__group">
          <label class="form__label">{{ form.description.label }}</label>
          <div class="form__field-group">
            {{ form.description }}
          </div>
        </div>
        <div class="form__group">
          <span class="form__label">Загрузить фото</span>
          <div class="form__field-group">
            {{ form.image|addclass:"form__file-button" }}
          </div>
        </div>
        <div class="form__footer">
          {% if edit %}
            <button class="button button_style_blue" type="submit">Сохранить</button>
            <a style="margin-left: 2.5em"
               href="{% url 'recipe_delete' recipe.slug %}"
               class="form__ingredient-link">Удалить
            </a>
          {% else %}
            <button class="button button_style_blue" type="submit">Создать рецепт</button>
          {% endif %}

        </div>
      </form>
    </div>


  </main>
{% endblock %}
{% block footer %}
  {% include "include/footer.html" %}
{% endblock %}

{% block style %}

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>
  <script src="{% static 'js/utils/debouncing.js' %}"></script>
  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

foodgram/templates/index.html
{% extends "include/base.html" %}

{% load user_filters %}
{% load static %}

{% block title %}Рецепты{% endblock %}

{% block css %}<link rel="stylesheet" href="{% static 'pages/index.css' %}"/>{% endblock %}

{% block header %}{% include "include/header.html" %}{% endblock %}

{% block content %}
  <main class="main container">
    <div class="main__header">
      <h1 class="main__title">Рецепты</h1>
      {% include 'include/tags.html' %}
    </div>
    <div class="card-list">
      {% for recipe in page %}
        {% include "include/recipe_card.html" %}
      {% endfor %}
    </div>
    {% if page.has_other_pages %}
      {% include "include/paginator.html" with items=page paginator=paginator %}
    {% endif %}
  </main>
{% endblock content %}
{% block footer %}
  {% include "include/footer.html" %}
{% endblock %}
{% block style %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>

  {% if user.is_authenticated %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
  {% endif %}

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>

  {% if user.is_authenticated %}
    <script src="{% static 'indexAuth.js' %}"></script>
  {% else %}
    <script src="{% static 'indexNotAuth.js' %}"></script>
  {% endif %}
{% endblock style %}

foodgram/templates/my_follow.html
{% extends "include/base.html" %}
{% load user_filters %}
{% block title %}Мои подписки{% endblock %}
{% load thumbnail %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}
{% block header %}
{% include "include/header.html" %}
{% endblock %}
{% block content %}
<body class="body">
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for follow in page %}
        <div class="card-user" data-author="{{ follow.author.id }}">
        <div class="card-user__header">
            <h2 class="card-user__title">{{ follow.author.get_full_name }}</h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">
                {% for recipe in follow.author.recipes.all|slice:"3" %}
                <li class="card-user__item">
                    <div class="recipe">
                        {% thumbnail recipe.image "480x480" as im %}
                            <a href="{% url 'recipe' recipe.slug %}"><img src="{{ im.url }}" alt="Картинка" class="recipe__image"></a>
                        {% endthumbnail %}
                        <h3 class="recipe__title">{{ recipe.name }}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time_cooking }} мин.</p>
                    </div>
                </li>
                {% endfor %}
                <li class="card-user__item">
                    {% if  follow.author.recipes.all.count > 3 %}
                        <a href="{% url 'author_recipe' follow.author %}" class="card-user__link link">{{ follow.author.recipes.all.count|follow_count }} </a>
                    {% endif %}
                </li>
            </ul>
        </div>
        <div class="card-user__footer">
          <a href="{% url 'follow' %}">
            <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
          </a>
        </div>
    </div>
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator%}
        {% endif %}
</main>
{% endblock content %}
{% block footer %}
{% include "include/footer.html" %}
{% endblock %}

{% block style %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock style %}
</body>